

# nom appli
spring:
  application:
    name: memebre-micro
  # Configuration BD
  datasource:
    url: jdbc:mysql://localhost:3306/amsdb # Url Mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # Ne pas laisser en prod (mettre update au début)
      ddl-auto: create-drop
# Reglage serveur
server:
  port: 10000